# render.yaml
services:
  # Frontend Service
  - type: web
    name: lumyna-frontend
    env: static
    rootDir: frontend
    buildCommand: |-
      npm install
      npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: CI
        value: "false"
      - key: REACT_APP_API_URL
        value: https://esg-backend-cg6e.onrender.com
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: REACT_APP_FIREBASE_PROJECT_ID
        sync: false
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false

  # Backend Service
  - type: web
    name: lumyna-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FRONTEND_URL
        value: https://esg-frontend-x7hy.onrender.com